# Generated by Django 4.1.13 on 2025-12-21 21:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryClassification',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('patient_bracelet_id', models.CharField(max_length=50, verbose_name='ID браслету пацієнта')),
                ('injury_type', models.CharField(max_length=100, verbose_name='Тип поранення')),
                ('severity', models.CharField(max_length=50, verbose_name='Важкість')),
                ('diagnosis', models.TextField(verbose_name='Діагноз')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='План лікування')),
                ('classification_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата класифікації')),
            ],
            options={
                'verbose_name': 'Класифікація поранення',
                'verbose_name_plural': 'Класифікації поранень',
                'db_table': 'injury_classifications',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('bracelet_id', models.CharField(max_length=50, unique=True, verbose_name='ID браслету')),
                ('injury_type', models.CharField(choices=[('Вогнепальне поранення', 'Вогнепальне поранення'), ('Осколкове поранення', 'Осколкове поранення'), ('Контузія', 'Контузія'), ('Опіки', 'Опіки'), ('Переломи', 'Переломи'), ("М'які тканини", "М'які тканини"), ('Внутрішні травми', 'Внутрішні травми'), ('Інше', 'Інше')], max_length=100, verbose_name='Тип поранення')),
                ('severity', models.CharField(choices=[('Легкий', 'Легкий'), ('Середній', 'Середній'), ('Важкий', 'Важкий'), ('Критичний', 'Критичний')], max_length=50, verbose_name='Важкість стану')),
                ('admission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прийому')),
                ('bed_number', models.CharField(blank=True, max_length=10, verbose_name='Номер ліжка')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Група крові')),
                ('status', models.CharField(default='На лікуванні', max_length=50, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('patient_bracelet_id', models.CharField(max_length=50, verbose_name='ID браслету пацієнта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час вимірювання')),
                ('heart_rate', models.IntegerField(verbose_name='Пульс (уд/хв)')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('blood_pressure_sys', models.IntegerField(default=120, verbose_name='Тиск систолічний')),
                ('blood_pressure_dia', models.IntegerField(default=80, verbose_name='Тиск діастолічний')),
                ('oxygen_saturation', models.IntegerField(verbose_name='Сатурація O₂ (%)')),
            ],
            options={
                'verbose_name': 'Життєві показники',
                'verbose_name_plural': 'Життєві показники',
                'db_table': 'vital_signs',
            },
        ),
    ]
