# Generated by Django 3.1.12 on 2025-12-26 17:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логін')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль (хеш)')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('role', models.CharField(choices=[('Лікар', 'Лікар'), ('Медсестра', 'Медсестра'), ('Адміністратор', 'Адміністратор'), ('Парамедик', 'Парамедик')], max_length=50, verbose_name='Роль')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Спеціалізація')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Останній вхід')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('avatar', models.CharField(default='👤', max_length=10, verbose_name='Аватар (emoji)')),
            ],
            options={
                'verbose_name': 'Медичний працівник',
                'verbose_name_plural': 'Медичні працівники',
                'db_table': 'medical_staff',
            },
        ),
    ]
