# Generated by Django 4.1.13 on 2025-12-21 21:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Назва обладнання')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR-код')),
                ('status', models.CharField(choices=[('working', 'Працює'), ('maintenance', 'На обслуговуванні'), ('broken', 'Зламано'), ('reserved', 'Зарезервовано')], default='working', max_length=50, verbose_name='Статус')),
                ('last_maintenance', models.DateField(verbose_name='Останнє обслуговування')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Розташування')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Виробник')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата придбання')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантія до')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('maintenance_history', models.TextField(blank=True, default='[]', verbose_name='Історія обслуговування')),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Назва медикаменту')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('unit', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
                ('critical_level', models.IntegerField(verbose_name='Критичний рівень')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Штрих-код')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Термін придатності')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Постачальник')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Медикамент',
                'verbose_name_plural': 'Медикаменти',
            },
        ),
    ]
