# Generated by Django 3.1.12 on 2025-12-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва обладнання')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR-код')),
                ('status', models.CharField(choices=[('working', 'Працює'), ('maintenance', 'На обслуговуванні'), ('broken', 'Зламано'), ('reserved', 'Зарезервовано')], default='working', max_length=50, verbose_name='Статус')),
                ('last_maintenance', models.DateField(verbose_name='Останнє обслуговування')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Розташування')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Виробник')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата придбання')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантія до')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('maintenance_history', models.TextField(blank=True, default='[]', verbose_name='Історія обслуговування')),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва медикаменту')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('unit', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
                ('critical_level', models.IntegerField(verbose_name='Критичний рівень')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Штрих-код')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Термін придатності')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Постачальник')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Медикамент',
                'verbose_name_plural': 'Медикаменти',
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_barcode', models.CharField(max_length=100, verbose_name='Штрих-код медикаменту')),
                ('action', models.CharField(choices=[('added', 'Додано'), ('used', 'Використано'), ('expired', 'Прострочено'), ('restocked', 'Поповнено')], max_length=50)),
                ('quantity_change', models.IntegerField(verbose_name='Зміна кількості')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час операції')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='Користувач')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
            options={
                'verbose_name': 'Лог медикаментів',
                'verbose_name_plural': 'Логи медикаментів',
                'ordering': ['-timestamp'],
            },
        ),
    ]
