# Generated by Django 4.1.13 on 2025-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR-код'),
        ),
    ]
